name: Build and Push Docker Image

on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_USERPASSWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ops-tools  # 设置构建上下文为当前目录
          file: ops-tools/Dockerfile
          push: true
          tags: fanhuadesnelin/ops-tools:latest