name: Build and Push Docker Image

on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_USERPASSWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # 设置构建上下文为当前目录
          push: true
          tags: fanhuadesnelin/ops-tools:latest