name: Build and Push Docker Image

on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
        # 设置 QEMU, 后面 docker buildx 依赖此.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # 设置 Docker buildx, 方便构建 Multi platform 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ops-tools  # 设置构建上下文为当前目录
          file: ops-tools/Dockerfile
          push: true
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          tags: |
            fanhuadesnelin/ops-tools:latest
            fanhuadesnelin/ops-tools:${{ env.APP_VERSION }}
